### ISSUE TITLE
Finish Auth

### ISSUE THREAD

**Issue by AK3030** [AK3030/MusicNimbus#12]

**Comment by niartenyaw** [comment]
Looks great!

## Functionality

- [x] `https://musicnimbus.herokuapp.com/#/erognoerign` should redirect back to `/`
- [x] Errors should clear when moving between `/signup` and `/login`
- [x] I was able to sign up with the same username, is that functionality that you want?

## Styling

Nice modal!

- [x] I think the modal could have less height and more width. I feel like it should be ~70 percent of the width and height of the viewport and centered for both.
- [x] You might want some kind of hover effect on all the buttons.

**Comment by AK3030** [comment]
Just finished those changes. Let me know if it needs anything else.

**Comment by niartenyaw** [comment]
Nice! Just one thing: 

- [ ] It would be nice to be able to click outside of the form to close the modal, instead of pressing the `X`. If you can't figure this out quickly, I wouldn't worry about it for now. Maybe create a separate issue and you can complete it later. After an attempt/completion, you can close this issue!
